import runsim_func
print("==========================")
print("simulation result of hovel")
print("==========================")
runsim_func.hovel_sim()
print("\n\n")
print("===========================")
print("simulation result of circle")
print("===========================")
runsim_func.circle_sim()
print("\n\n")
print("============================")
print("simulation result of diamond")
print("============================")
runsim_func.diamond_sim()
print("\n\n")
print("========================")
print("simulation result of tud")
print("========================")
runsim_func.tud_sim()